production:
  adapter: postgresql
  encoding: unicode
  database: mysite_production
  pool: 200
  username: moshe
  password: blat
  prepared_statements: false

staging:
  adapter: postgresql
  encoding: unicode
  database: mysite_staging
  pool: 100
  username: moshe
  password: blat
  prepared_statements: false

development:
  adapter: postgresql
  encoding: unicode
  database: mysite_dev
  pool: 100
  username: oren
  password:
  prepared_statements: false

test:
  adapter: postgresql
  encoding: unicode
  database: mysite_test
  pool: 10
  timeout: 5000
  username: 
  password:


